### ISSUE TITLE
Query about some training details

### ISSUE THREAD

**Issue by Exuan148** [Xiaojiu-z/SSR_Encoder#1]
Good noon!
I would like to ask you that if the text query (which is input into SSR-encoder) and the text prompt (which is input into U-net cross-attention layers) are the same while you were training? 
Also, I would like to ask did you always use mask (in token-to-patch aligner) while training?
Thanks you!

**Comment by Xiaojiu-z** [comment]
Yep, there are the same (or you can try tagger for the text query) and we didn't use mask to assist training.

**Comment by Xiaojiu-z** [comment]
Yep, they are the same (or you can use tagger for text query) and we didn't use mask to assist training.
