### ISSUE TITLE
Any plan to open source Multi-subject bench?

### ISSUE THREAD

**Issue by tingxueronghua** [Xiaojiu-z/SSR_Encoder#2]
As described in the title. 

It would be great to provide the benchmark so that other researchers could compare their methods with yours. Otherwise, a new benchmark is needed and your method might be evaluated unfairly.

**Comment by Xiaojiu-z** [comment]
> As described in the title.
> 
> It would be great to provide the benchmark so that other researchers could compare their methods with yours. Otherwise, a new benchmark is needed and your method might be evaluated unfairly.

Unfortunately, due to some restrictions, all the data is not publicly available, but similar datasets are easily available with a few simple filters.
