### ISSUE TITLE
A bug in function "generate_multi"

### ISSUE THREAD

**Issue by HorizonWind2004** [Xiaojiu-z/SSR_Encoder#3]
A very nice work! But I found a mistake when I try to inference with the script "infer_multi.py".

It seem that the list "scales" doesn't work. When I change the scale[1], scale[2], the generated image doesn't change.

So I try to debug, print the image_prompt_embed_new and find that:

```python
for i in range(len(scale)):
            image_prompt_embed_new = scale[i] * image_prompt_embeds[:, int(77 * self.num * i * 6): \
                                            int(77 * self.num * (i+1) * 6), :]
            print(image_prompt_embed_new)
            image_prompt_embed = image_prompt_embed_new
            cache.append(image_prompt_embed)

output:
tensor([[[-0.1298,  0.1105, -0.0797,  ..., -0.1443, -0.1312,  0.0391],
         [-0.1351,  0.1661,  0.4278,  ..., -0.3885, -0.0361, -0.2958],
         [-0.2923,  0.0340,  0.0106,  ...,  0.0062, -0.2486, -0.2061],
         ...,
         [-0.0492,  0.0397, -0.8274,  ..., -0.1983, -0.3286,  0.0879],
         [-0.0479,  0.0378, -0.8244,  ..., -0.1965, -0.3283,  0.0885],
         [-0.0506,  0.0350, -0.8217,  ..., -0.1985, -0.3244,  0.0805]]],
       device='cuda:0')
tensor([], device='cuda:0', size=(1, 0, 768))
tensor([], device='cuda:0', size=(1, 0, 768))
```

I think you had made a mistake when you wrote this code. You probably should do "get_image_embeds" for "self.num" times.

Thank you!

**Comment by Xiaojiu-z** [comment]
> A very nice work! But I found a mistake when I try to inference with the script "infer_multi.py".
> 
> It seem that the list "scales" doesn't work. When I change the scale[1], scale[2], the generated image doesn't change.
> 
> So I try to debug, print the image_prompt_embed_new and find that:
> 
> ```python
> for i in range(len(scale)):
>             image_prompt_embed_new = scale[i] * image_prompt_embeds[:, int(77 * self.num * i * 6): \
>                                             int(77 * self.num * (i+1) * 6), :]
>             print(image_prompt_embed_new)
>             image_prompt_embed = image_prompt_embed_new
>             cache.append(image_prompt_embed)
> 
> output:
> tensor([[[-0.1298,  0.1105, -0.0797,  ..., -0.1443, -0.1312,  0.0391],
>          [-0.1351,  0.1661,  0.4278,  ..., -0.3885, -0.0361, -0.2958],
>          [-0.2923,  0.0340,  0.0106,  ...,  0.0062, -0.2486, -0.2061],
>          ...,
>          [-0.0492,  0.0397, -0.8274,  ..., -0.1983, -0.3286,  0.0879],
>          [-0.0479,  0.0378, -0.8244,  ..., -0.1965, -0.3283,  0.0885],
>          [-0.0506,  0.0350, -0.8217,  ..., -0.1985, -0.3244,  0.0805]]],
>        device='cuda:0')
> tensor([], device='cuda:0', size=(1, 0, 768))
> tensor([], device='cuda:0', size=(1, 0, 768))
> ```
> 
> I think you had made a mistake when you wrote this code. You probably should do "get_image_embeds" for "self.num" times.
> 
> Thank you!

It worked on my computer 🤔. Did you notice that all image features will be concat when entered as a list? It looks like you only used one image, but you set nums to 3.

**Comment by Parul-Gupta** [comment]
Hello SSR-Encoder authors, Kudos for this amazing work!

I had a related question in the multi_infer script: When doing multi-subject sampling, how to intuitively set each of these scale values?

Does it depend upon relative size of the input image and the generated image? Or does it indicate the ratio between the input image size and the size of that object in the target image? How does this weightage of the clip embedding affect the output?

e.g. if we pass the scale as [1.0, 1.0] for two object images (first image is 100x100 and second image is 400x400, and the generated image size is set to 512x512), would it mean they will be of same size in the generated image, or would it mean the first object is 1/4th of the second object in the generated image?

Edit: I have observed that keeping everything else the same, if we are generating an image using two object images, the second scale value has no effect on the outcome whatsoever. Similarly, using three objects, the second and third scale values have no effect on the output image.
