### ISSUE TITLE
Meet error when loading checkpoints for ssr_model

### ISSUE THREAD

**Issue by cc13qq** [Xiaojiu-z/SSR_Encoder#6]
RuntimeError: Error(s) in loading state_dict for ModuleList:
        Missing key(s) in state_dict: "33.to_k_SSR.weight", "33.to_v_SSR.weight", "35.to_k_SSR.weight", "35.to_v_SSR.weight", "37.to_k_SSR.weight", "37.to_v_SSR.weight", "39.to_k_SSR.weight", "39.to_v_SSR.weight", "41.to_k_SSR.weight", "41.to_v_SSR.weight", "43.to_k_SSR.weight", "43.to_v_SSR.weight", "45.to_k_SSR.weight", "45.to_v_SSR.weight", "47.to_k_SSR.weight", "47.to_v_SSR.weight", "49.to_k_SSR.weight", "49.to_v_SSR.weight", "51.to_k_SSR.weight", "51.to_v_SSR.weight", "53.to_k_SSR.weight", "53.to_v_SSR.weight", "55.to_k_SSR.weight", "55.to_v_SSR.weight", "57.to_k_SSR.weight", "57.to_v_SSR.weight", "59.to_k_SSR.weight", "59.to_v_SSR.weight", "61.to_k_SSR.weight", "61.to_v_SSR.weight", "63.to_k_SSR.weight", "63.to_v_SSR.weight", "65.to_k_SSR.weight", "65.to_v_SSR.weight", "67.to_k_SSR.weight", "67.to_v_SSR.weight", "69.to_k_SSR.weight", "69.to_v_SSR.weight", "71.to_k_SSR.weight", "71.to_v_SSR.weight", "73.to_k_SSR.weight", "73.to_v_SSR.weight", "75.to_k_SSR.weight", "75.to_v_SSR.weight", "77.to_k_SSR.weight", "77.to_v_SSR.weight", "79.to_k_SSR.weight", "79.to_v_SSR.weight", "81.to_k_SSR.weight", "81.to_v_SSR.weight", "83.to_k_SSR.weight", "83.to_v_SSR.weight", "85.to_k_SSR.weight", "85.to_v_SSR.weight", "87.to_k_SSR.weight", "87.to_v_SSR.weight", "89.to_k_SSR.weight", "89.to_v_SSR.weight", "91.to_k_SSR.weight", "91.to_v_SSR.weight", "93.to_k_SSR.weight", "93.to_v_SSR.weight", "95.to_k_SSR.weight", "95.to_v_SSR.weight", "97.to_k_SSR.weight", "97.to_v_SSR.weight", "99.to_k_SSR.weight", "99.to_v_SSR.weight", "101.to_k_SSR.weight", "101.to_v_SSR.weight", "103.to_k_SSR.weight", "103.to_v_SSR.weight", "105.to_k_SSR.weight", "105.to_v_SSR.weight", "107.to_k_SSR.weight", "107.to_v_SSR.weight", "109.to_k_SSR.weight", "109.to_v_SSR.weight", "111.to_k_SSR.weight", "111.to_v_SSR.weight", "113.to_k_SSR.weight", "113.to_v_SSR.weight", "115.to_k_SSR.weight", "115.to_v_SSR.weight", "117.to_k_SSR.weight", "117.to_v_SSR.weight", "119.to_k_SSR.weight", "119.to_v_SSR.weight", "121.to_k_SSR.weight", "121.to_v_SSR.weight", "123.to_k_SSR.weight", "123.to_v_SSR.weight", "125.to_k_SSR.weight", "125.to_v_SSR.weight", "127.to_k_SSR.weight", "127.to_v_SSR.weight", "129.to_k_SSR.weight", "129.to_v_SSR.weight", "131.to_k_SSR.weight", "131.to_v_SSR.weight", "133.to_k_SSR.weight", "133.to_v_SSR.weight", "135.to_k_SSR.weight", "135.to_v_SSR.weight", "137.to_k_SSR.weight", "137.to_v_SSR.weight", "139.to_k_SSR.weight", "139.to_v_SSR.weight". 
        size mismatch for 1.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 1.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 3.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 3.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 5.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 5.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 7.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 7.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]).
        size mismatch for 9.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 9.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 11.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 11.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 13.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 13.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 15.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 15.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 17.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 17.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 19.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 19.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 21.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 21.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 23.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 23.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 25.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 25.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 27.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 27.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 29.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 29.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 31.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).
        size mismatch for 31.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).

**Comment by HoyaAm** [comment]
> RuntimeError: Error(s) in loading state_dict for ModuleList: Missing key(s) in state_dict: "33.to_k_SSR.weight", "33.to_v_SSR.weight", "35.to_k_SSR.weight", "35.to_v_SSR.weight", "37.to_k_SSR.weight", "37.to_v_SSR.weight", "39.to_k_SSR.weight", "39.to_v_SSR.weight", "41.to_k_SSR.weight", "41.to_v_SSR.weight", "43.to_k_SSR.weight", "43.to_v_SSR.weight", "45.to_k_SSR.weight", "45.to_v_SSR.weight", "47.to_k_SSR.weight", "47.to_v_SSR.weight", "49.to_k_SSR.weight", "49.to_v_SSR.weight", "51.to_k_SSR.weight", "51.to_v_SSR.weight", "53.to_k_SSR.weight", "53.to_v_SSR.weight", "55.to_k_SSR.weight", "55.to_v_SSR.weight", "57.to_k_SSR.weight", "57.to_v_SSR.weight", "59.to_k_SSR.weight", "59.to_v_SSR.weight", "61.to_k_SSR.weight", "61.to_v_SSR.weight", "63.to_k_SSR.weight", "63.to_v_SSR.weight", "65.to_k_SSR.weight", "65.to_v_SSR.weight", "67.to_k_SSR.weight", "67.to_v_SSR.weight", "69.to_k_SSR.weight", "69.to_v_SSR.weight", "71.to_k_SSR.weight", "71.to_v_SSR.weight", "73.to_k_SSR.weight", "73.to_v_SSR.weight", "75.to_k_SSR.weight", "75.to_v_SSR.weight", "77.to_k_SSR.weight", "77.to_v_SSR.weight", "79.to_k_SSR.weight", "79.to_v_SSR.weight", "81.to_k_SSR.weight", "81.to_v_SSR.weight", "83.to_k_SSR.weight", "83.to_v_SSR.weight", "85.to_k_SSR.weight", "85.to_v_SSR.weight", "87.to_k_SSR.weight", "87.to_v_SSR.weight", "89.to_k_SSR.weight", "89.to_v_SSR.weight", "91.to_k_SSR.weight", "91.to_v_SSR.weight", "93.to_k_SSR.weight", "93.to_v_SSR.weight", "95.to_k_SSR.weight", "95.to_v_SSR.weight", "97.to_k_SSR.weight", "97.to_v_SSR.weight", "99.to_k_SSR.weight", "99.to_v_SSR.weight", "101.to_k_SSR.weight", "101.to_v_SSR.weight", "103.to_k_SSR.weight", "103.to_v_SSR.weight", "105.to_k_SSR.weight", "105.to_v_SSR.weight", "107.to_k_SSR.weight", "107.to_v_SSR.weight", "109.to_k_SSR.weight", "109.to_v_SSR.weight", "111.to_k_SSR.weight", "111.to_v_SSR.weight", "113.to_k_SSR.weight", "113.to_v_SSR.weight", "115.to_k_SSR.weight", "115.to_v_SSR.weight", "117.to_k_SSR.weight", "117.to_v_SSR.weight", "119.to_k_SSR.weight", "119.to_v_SSR.weight", "121.to_k_SSR.weight", "121.to_v_SSR.weight", "123.to_k_SSR.weight", "123.to_v_SSR.weight", "125.to_k_SSR.weight", "125.to_v_SSR.weight", "127.to_k_SSR.weight", "127.to_v_SSR.weight", "129.to_k_SSR.weight", "129.to_v_SSR.weight", "131.to_k_SSR.weight", "131.to_v_SSR.weight", "133.to_k_SSR.weight", "133.to_v_SSR.weight", "135.to_k_SSR.weight", "135.to_v_SSR.weight", "137.to_k_SSR.weight", "137.to_v_SSR.weight", "139.to_k_SSR.weight", "139.to_v_SSR.weight". size mismatch for 1.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 1.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 3.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 3.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 5.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 5.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 7.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 7.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([640, 2048]). size mismatch for 9.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 9.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 11.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 11.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 13.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 13.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 15.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 15.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 17.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 17.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 19.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 19.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 21.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 21.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 23.to_k_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 23.to_v_SSR.weight: copying a param with shape torch.Size([640, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 25.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 25.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 27.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 27.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 29.to_k_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 29.to_v_SSR.weight: copying a param with shape torch.Size([320, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 31.to_k_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]). size mismatch for 31.to_v_SSR.weight: copying a param with shape torch.Size([1280, 768]) from checkpoint, the shape in current model is torch.Size([1280, 2048]).

Hello, could you tell me  how to solve this problem?
